
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.23.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------

using Terminal.Gui;

namespace PersistedMetadata {
    public partial class MessageWindow : Terminal.Gui.Window {
        
        private Terminal.Gui.Window send;
        
        private Terminal.Gui.Label msgTxtLabel;
        
        private Terminal.Gui.TextField msgText;
        
        private Terminal.Gui.Button sendGreeting;
        
        private Terminal.Gui.Button sendFarewell;
        
        private Terminal.Gui.Label senderNameLabel;
        
        private Terminal.Gui.Label senderName;
        
        private Terminal.Gui.Window receive;
        
        private Terminal.Gui.Label msgTypeLabel;
        
        private Terminal.Gui.Label msgType;
        
        private Terminal.Gui.Label msgTextReceivedLabel;
        
        private Terminal.Gui.Label msgTextReceived;
        
        private Terminal.Gui.Label msgFromLabel;
        
        private Terminal.Gui.Label msgFrom;
        
        private Terminal.Gui.Button quit;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem loginMenu;
        
        private Terminal.Gui.MenuItem editMeMenuItem1;
        
        private Terminal.Gui.MenuItem editMeMenuItem2;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.quit = new Terminal.Gui.Button();
            this.msgFrom = new Terminal.Gui.Label();
            this.msgFromLabel = new Terminal.Gui.Label();
            this.msgTextReceived = new Terminal.Gui.Label();
            this.msgTextReceivedLabel = new Terminal.Gui.Label();
            this.msgType = new Terminal.Gui.Label();
            this.msgTypeLabel = new Terminal.Gui.Label();
            this.receive = new Terminal.Gui.Window();
            this.senderName = new Terminal.Gui.Label();
            this.senderNameLabel = new Terminal.Gui.Label();
            this.sendFarewell = new Terminal.Gui.Button();
            this.sendGreeting = new Terminal.Gui.Button();
            this.msgText = new Terminal.Gui.TextField();
            this.msgTxtLabel = new Terminal.Gui.Label();
            this.send = new Terminal.Gui.Window();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.White;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Message Poster";
            this.send.Width = Dim.Percent(50f);
            this.send.Height = Dim.Fill(2);
            this.send.X = 0;
            this.send.Y = 2;
            this.send.Modal = false;
            this.send.Data = "send";
            this.send.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.send.Border.BorderBrush = Terminal.Gui.Color.White;
            this.send.Border.Effect3D = false;
            this.send.Border.Effect3DBrush = null;
            this.send.Border.DrawMarginFrame = true;
            this.send.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.send.Title = "Send";
            this.Add(this.send);
            this.msgTxtLabel.Width = 3;
            this.msgTxtLabel.Height = 1;
            this.msgTxtLabel.X = 0;
            this.msgTxtLabel.Y = 0;
            this.msgTxtLabel.Data = "label";
            this.msgTxtLabel.Text = "Message";
            this.msgTxtLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.send.Add(this.msgTxtLabel);
            this.msgText.Width = 10;
            this.msgText.Height = 1;
            this.msgText.X = 10;
            this.msgText.Y = 0;
            this.msgText.Secret = false;
            this.msgText.Data = "msgText";
            this.msgText.Text = "Aloha!";
            this.msgText.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.send.Add(this.msgText);
            this.sendGreeting.Width = 17;
            this.sendGreeting.Height = 1;
            this.sendGreeting.X = 0;
            this.sendGreeting.Y = 2;
            this.sendGreeting.Data = "sendGreeting";
            this.sendGreeting.Text = "Send Greeting";
            this.sendGreeting.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.sendGreeting.IsDefault = false;
            this.send.Add(this.sendGreeting);
            this.sendFarewell.Width = 17;
            this.sendFarewell.Height = 1;
            this.sendFarewell.X = 0;
            this.sendFarewell.Y = 3;
            this.sendFarewell.Data = "sendFarewell";
            this.sendFarewell.Text = "Send Farewell";
            this.sendFarewell.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.sendFarewell.IsDefault = false;
            this.send.Add(this.sendFarewell);
            this.senderNameLabel.Width = 7;
            this.senderNameLabel.Height = 10;
            this.senderNameLabel.X = 0;
            this.senderNameLabel.Y = 11;
            this.senderNameLabel.Data = "senderNameLabel";
            this.senderNameLabel.Text = "Sender";
            this.senderNameLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.send.Add(this.senderNameLabel);
            this.senderName.Width = 10;
            this.senderName.Height = 1;
            this.senderName.X = 12;
            this.senderName.Y = 11;
            this.senderName.Data = "senderName";
            this.senderName.Text = "";
            this.senderName.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.send.Add(this.senderName);
            this.receive.Width = Dim.Percent(50f);
            this.receive.Height = Dim.Fill(2);
            this.receive.X = Pos.Right(send);
            this.receive.Y = 2;
            this.receive.Modal = false;
            this.receive.Data = "receive";
            this.receive.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.receive.Border.BorderBrush = Terminal.Gui.Color.White;
            this.receive.Border.Effect3D = false;
            this.receive.Border.Effect3DBrush = null;
            this.receive.Border.DrawMarginFrame = true;
            this.receive.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.receive.Title = "Receive";
            this.Add(this.receive);
            this.msgTypeLabel.Width = 4;
            this.msgTypeLabel.Height = 1;
            this.msgTypeLabel.X = 0;
            this.msgTypeLabel.Y = 0;
            this.msgTypeLabel.Data = "msgTypeLabel";
            this.msgTypeLabel.Text = "Type";
            this.msgTypeLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.receive.Add(this.msgTypeLabel);
            this.msgType.Width = 10;
            this.msgType.Height = 1;
            this.msgType.X = 11;
            this.msgType.Y = 0;
            this.msgType.Data = "msgType";
            this.msgType.Text = "[msg type]";
            this.msgType.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.receive.Add(this.msgType);
            this.msgTextReceivedLabel.Width = 6;
            this.msgTextReceivedLabel.Height = 1;
            this.msgTextReceivedLabel.X = 0;
            this.msgTextReceivedLabel.Y = 2;
            this.msgTextReceivedLabel.Data = "msgTextReceivedLabel";
            this.msgTextReceivedLabel.Text = "Message";
            this.msgTextReceivedLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.receive.Add(this.msgTextReceivedLabel);
            this.msgTextReceived.Width = 10;
            this.msgTextReceived.Height = 1;
            this.msgTextReceived.X = 11;
            this.msgTextReceived.Y = 2;
            this.msgTextReceived.Data = "msgTextReceived";
            this.msgTextReceived.Text = "[text recived]";
            this.msgTextReceived.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.receive.Add(this.msgTextReceived);
            this.msgFromLabel.Width = 5;
            this.msgFromLabel.Height = 1;
            this.msgFromLabel.X = 0;
            this.msgFromLabel.Y = 4;
            this.msgFromLabel.Data = "msgFromLabel";
            this.msgFromLabel.Text = "Sender";
            this.msgFromLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.receive.Add(this.msgFromLabel);
            this.msgFrom.Width = 10;
            this.msgFrom.Height = 1;
            this.msgFrom.X = 11;
            this.msgFrom.Y = 4;
            this.msgFrom.Data = "msgFrom";
            this.msgFrom.Text = "[msg from]";
            this.msgFrom.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.receive.Add(this.msgFrom);
            this.quit.Width = 8;
            this.quit.Height = 1;
            this.quit.X = Pos.AnchorEnd(10);
            this.quit.Y = Pos.AnchorEnd(1);
            this.quit.Data = "quit";
            this.quit.Text = "Quit";
            this.quit.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.quit.IsDefault = false;
            this.Add(this.quit);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = -1;
            this.menuBar.Y = 0;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.loginMenu = new Terminal.Gui.MenuBarItem();
            this.loginMenu.Title = "_Login";
            this.editMeMenuItem1 = new Terminal.Gui.MenuItem();
            this.editMeMenuItem1.Title = "Alice";
            this.editMeMenuItem1.Data = "editMeMenuItem1";
            this.editMeMenuItem2 = new Terminal.Gui.MenuItem();
            this.editMeMenuItem2.Title = "Bob";
            this.editMeMenuItem2.Data = "editMeMenuItem2";
            this.loginMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem1,
                    this.editMeMenuItem2};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.loginMenu};
            this.Add(this.menuBar);
        }
    }
}
