<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(LibTargetFrameworks)</TargetFrameworks>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\ReactiveDomain.Core\ReactiveDomain.Core.csproj" />
		<ProjectReference Include="..\ReactiveDomain.Messaging\ReactiveDomain.Messaging.csproj" />
	</ItemGroup>
</Project>